spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/salon-app
  datasource:
    keycloak:
      name: keycloak_v1
      username: postgres
      password: ***
      url: jdbc:postgresql://localhost:5436/keycloak_v1
      driver-class-name: org.postgresql.Driver
    postgres:
      name: postgres
      username: postgres
      password: ***
      url: jdbc:postgresql://localhost:5436/postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  keycloak:
    client-id: back-end
    client-secret: *******
    realm: salon-app
    server-url: http://localhost:9090/

server:
  port: 8080
  servlet:
    context-path: /api/

application:
  file:
    uploads:
      photos-output-path: ./uploads
logging:
  level:
    web: debug
